[global]
# Turn off file watcher and development features
developmentMode = false
disableWatchdogWarning = true

[browser]
# Clean up the browser interface
gatherUsageStats = false

[server]
# Production-like settings
headless = true
fileWatcherType = "none"