# PropelAuth Configuration for Streamlit
PROPELAUTH_URL = "https://34521247761.propelauthtest.com"
BACKEND_URL = "http://localhost:8002"

# Native Streamlit OAuth Configuration
[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "o_6fdvkfS9_dSFMDISJoBUA9FtEDL0oo-ZDgZWt9l38"
client_id = "4e68fdae569be0db0211f668f191c188"
client_secret = "24a00467b2ae85f1ded7393b3e812529c16728588ee149c938f7766d5d577cb0e0c539310d1d03eff2246cbd603de998"
server_metadata_url = "https://34521247761.propelauthtest.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }