# PropelAuth Configuration for Streamlit
PROPELAUTH_URL = "https://34521247761.propelauthtest.com"
BACKEND_URL = "http://localhost:8002"
PROPELAUTH_API_KEY = "1a5b7f972cd7bd3554dbea35e64757787376e2b07a2907545592fcbb4b427f122995bb05b2c974eca46c536e16d44b33"
PROPELAUTH_CLIENT_ID = "4a68fdae569be0db02111668f191c188"
PROPELAUTH_CLIENT_SECRET = "8832b7f3321ff23a54aa77ec5289489ee2164ecf910cb8f6720dea4ba391dafbb662f640432fa8f1b993170bf7c1e4e8"
PROPELAUTH_VERIFIER_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx9ja3PuI+4KfgR5j7hbS
3W/u4/9gI2ZOt3dH2zo4sBDiTAn3gHQj8NTU1xdQfhX7Rz7lza65CwRD6E0tveLV
CUw5YwWzVeGdHtV5idVoC8VbYnIiR7mdlPNbJlE3srqOQy/y8qj/mBByT4HrYbhY
D1i3I/EkB4I+8ZYhGCTJ4G/pLlhYf0n7CJ7fA4aGJ5apVrevJO4z6L+K1F+KBuL+
oqvYbu4IkGXNUXrXk7kHHLnBIbfrQ4/eu6JJzGmMZAX+vhvhNLTFwoDA0Ij8NZPZ
TLcWdq3VjN2XVd3PF357nZ0H9cpUE+4m3dvGuTC8ByE+hAUv9L4w+FPBuS4OYtw5
EwIDAQAB
-----END PUBLIC KEY-----"""